baseURL = 'https://library.techliterate.co/fundamentals'
languageCode = 'en-us'
title = 'Tech Fundamentals'
theme = 'hugo-theme-relearn'

[params]
  author.emailname = 'chris@techliterate.co'
  author.name = 'Christer Edwards'
  disableLanguages = ['pir']
  disableSearchHiddenPages = true
  disableSeoHiddenPages = true
  disableTagHiddenPages = true
  editURL = "https://forgejo.iniquity.io/cedwards/techliterate.co-fundamentals/_edit/main/content/${FilePath}"
  mermaidInitialize = '{ "flowchart": { "useMaxWidth": false, "nodeSpacing": 40, "rankSpacing": 70, "htmlLabels": true } }'
  mermaidZoom = true
  showVisitedLinks = true
  titleSeparator = ':'

[[params.themeVariant]]
  identifier = 'auto'

[[params.themeVariant]]
  identifier = 'zen-dark'

[[params.themeVariant]]
    identifier = 'zen-light'

[[params.themeVariant]]
  identifier = 'relearn-dark'

[[params.themeVariant]]
  identifier = 'relearn-light'


[outputs]
  home = ['html', 'rss', 'markdown', 'source', 'print']
  page = ['html', 'markdown', 'source', 'print']
  section = ['html', 'rss', 'markdown', 'source', 'print']

##[menu]
##  [[menu.shortcuts]]
##    name = 'Appendix'
##    url = '//appendix'
##    weight = 1
##  [[menu.shortcuts]]
##    name = 'Second'
##    url = '//second'
##    weight = 2
